# Generated by Django 4.0.5 on 2022-07-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('NombreMedic', models.CharField(max_length=150, verbose_name='Nombre del Medicamento')),
                ('Descripcion', models.TextField()),
                ('clave', models.CharField(max_length=150, verbose_name='Clave')),
                ('FechaCad', models.CharField(max_length=50, verbose_name='Fecha de Caducidad')),
                ('stock', models.CharField(max_length=100, verbose_name='Stock')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('imagen', models.ImageField(null=True, upload_to='fotos', verbose_name='Imagen del Curso')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['created'],
            },
        ),
    ]
