# Generated by Django 4.0.5 on 2022-07-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_alter_medicamentos_stock_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentos',
            name='stock',
            field=models.CharField(max_length=50, verbose_name='Stock'),
        ),
    ]
