# Generated by Django 4.0.5 on 2022-07-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_medicamentos_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos', verbose_name='Imagen del Curso'),
        ),
        migrations.DeleteModel(
            name='Salida',
        ),
    ]
