# Generated by Django 4.0.5 on 2022-07-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_remove_medicamentos_clave_alter_medicamentos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentos',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='fotos', verbose_name='Imagen del Curso'),
        ),
    ]
