# Generated by Django 4.0.5 on 2022-07-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_alter_medicamentos_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('NombreMedic', models.CharField(max_length=150, verbose_name='Nombre del Medicamento')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('Descripcion', models.TextField()),
                ('FechaCad', models.CharField(max_length=50, verbose_name='Fecha de Caducidad')),
                ('stock', models.CharField(max_length=50, verbose_name='Stock')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('imagen', models.FileField(blank=True, null=True, upload_to='fotos', verbose_name='Imagen del Curso')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['created'],
            },
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos', verbose_name='Imagen del Curso'),
        ),
    ]
