# Generated by Django 4.0.5 on 2022-07-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_archivos_alter_medicamentos_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivos',
            name='imagen',
        ),
        migrations.AddField(
            model_name='archivos',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='fotos', verbose_name='Imagen'),
        ),
    ]
