# Generated by Django 4.0.5 on 2022-07-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_alter_archivos_archivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archivos',
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Imagen del Curso'),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='stock',
            field=models.IntegerField(verbose_name='Stock'),
        ),
    ]
