# Generated by Django 4.0.5 on 2022-07-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0011_archivos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivos',
            name='titulo',
        ),
        migrations.AddField(
            model_name='archivos',
            name='NombreMedic',
            field=models.CharField(max_length=150, null=True, verbose_name='Nombre del Medicamento'),
        ),
        migrations.AddField(
            model_name='archivos',
            name='categoria',
            field=models.CharField(max_length=100, null=True, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='archivos',
            name='fechaCad',
            field=models.CharField(max_length=50, null=True, verbose_name='Fecha de Caducidad'),
        ),
        migrations.AddField(
            model_name='archivos',
            name='status',
            field=models.CharField(max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='archivos',
            name='stock',
            field=models.IntegerField(null=True, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='archivos',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
