# Generated by Django 4.0.5 on 2022-07-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0013_archivos_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
