# Generated by Django 4.0.5 on 2022-08-09 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0015_remove_archivos_nombremedic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivos',
            options={'ordering': ['-created'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.CreateModel(
            name='SalidaMedicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AsignadoA', models.CharField(max_length=100)),
                ('Fecha', models.DateField()),
                ('Cantidad', models.IntegerField()),
                ('Medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.medicamentos')),
            ],
            options={
                'verbose_name': 'Salida Medicamentos',
                'verbose_name_plural': 'Salidas Medicamentos',
            },
        ),
    ]
