# Generated by Django 4.0.5 on 2022-08-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0016_alter_archivos_options_salidamedicamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidamedicamentos',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos', verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='salidamedicamentos',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='salidamedicamentos',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
    ]
