# Generated by Django 4.0.5 on 2022-08-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0017_salidamedicamentos_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidamedicamentos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
