# Generated by Django 4.0.5 on 2022-08-17 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0018_alter_salidamedicamentos_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salidamedicamentos',
            old_name='archivo',
            new_name='archivo2',
        ),
    ]
