# Generated by Django 4.0.5 on 2022-08-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0019_rename_archivo_salidamedicamentos_archivo2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidamedicamentos',
            name='Fecha',
            field=models.CharField(max_length=100),
        ),
    ]
