# Generated by Django 4.0.5 on 2022-08-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0020_alter_salidamedicamentos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidamedicamentos',
            name='Medicamento',
            field=models.CharField(max_length=100),
        ),
    ]
